# Config file for automatic testing at travis-ci.org
os: linux
dist: xenial
language: python
cache: pip
env:
  global:
    - FLASK_APP=autoapp.py
    - FLASK_DEBUG=1
python: 3.7
# TODO Database and code coverage later
#services:
#  - postgresql
#addons:
#  postgresql: "9.6"
#  hosts:
#  - postgresql
install:
  - pip3 install --upgrade pip poetry coveralls pre-commit
  - poetry install --no-ansi --no-interaction
before_script:
  - pip freeze
#  - psql -U postgres -c 'CREATE USER tegenaria;'
#  - psql -U postgres -c 'CREATE DATABASE tegenaria_test;'
#  - psql -U postgres -c 'GRANT ALL PRIVILEGES ON DATABASE tegenaria_test TO tegenaria;'
script:
  - pre-commit run --all-files
#after_success:
#  - codecov
after_failure:
  - dmesg | tail -n 100
