# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
dist: trusty
language: python
cache: pip
env:
- FLASK_APP=autoapp.py FLASK_DEBUG=1
python:
  - 3.6
# TODO Database and code coverage later
#services:
#  - postgresql
#addons:
#  postgresql: "9.6"
#  hosts:
#  - postgresql
install:
#  - pip install codecov
  - pip install -r requirements/dev.txt
before_script:
  - pip freeze
#  - psql -U postgres -c 'CREATE USER tegenaria;'
#  - psql -U postgres -c 'CREATE DATABASE tegenaria_test;'
#  - psql -U postgres -c 'GRANT ALL PRIVILEGES ON DATABASE tegenaria_test TO tegenaria;'
before_script:
  - flask lint
script: flask test
#after_success:
#  - codecov
after_failure:
  - dmesg | tail -n 100

# https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
notifications:
  email:
    on_success: never
