postgresql:
  # Official PostgreSQL image
  # https://registry.hub.docker.com/u/library/postgres/
  #
  # To run the database initialization again, you have to remove the containers and images. Use this command:
  # docker rm -f $(docker ps -a | grep -i tegenaria_postgresql | awk '{print $1}')
  # docker rmi -f tegenaria_postgresql
  #
  # To load data from SQLite, run this command:
  # ./manage.py db_refresh && pgloader -v docker/postgres/sqlite.load
  #
  # http://pgloader.io/howto/pgloader.1.html
  # https://github.com/dimitri/pgloader
  image: postgres:9.6.2
  environment:
    - POSTGRES_USER=tegenaria
    - POSTGRES_PASSWORD=tegenaria
  # https://docs.docker.com/compose/compose-file/#/expose
  expose:
    - "5432"
  # https://docs.docker.com/compose/compose-file/#/ports
  ports:
    - "5434:5432"
  volumes:
    - ./docker/postgres:/docker-entrypoint-initdb.d
